### ISSUE TITLE
Where can I find '/media/ssd4/hxy/BadCLIP/data/GCC_Training500K/images/3489869375.png'?

### ISSUE THREAD

**Issue by jackhexiangyu12** [LiangSiyuan21/BadCLIP#3]
(/media/ssd4/hxy/BadCLIP/env) hxy@thor:/media/ssd4/hxy/BadCLIP$ python -u src/embeding_optimize_patch.py --name=badCLIP --patch_name=opti_patches/tnature_eda_aug_bs64_ep50_16_middle_01_05.jpg --patch_size=16 --patch_location=middle --eda_prob=0.1 --aug_prob=0.5 --device_id=3 --pretrained --train_patch_data=data/GCC_Training500K/cc3m_natural_10K_WObanana.csv --batch_size=64 --epochs=50 --prog=2
2024-09-24,07:44:12 | INFO | Using cuda:3 device
2024-09-24,07:44:12 | INFO | Params:
2024-09-24,07:44:12 | INFO | add_backdoor: False
2024-09-24,07:44:12 | INFO | asr: False
2024-09-24,07:44:12 | INFO | aug_prob: 0.5
2024-09-24,07:44:12 | INFO | backdoor_sufi: False
2024-09-24,07:44:12 | INFO | batch_size: 64
2024-09-24,07:44:12 | INFO | beta1: 0.9
2024-09-24,07:44:12 | INFO | beta2: 0.999
2024-09-24,07:44:12 | INFO | blended_alpha: None
2024-09-24,07:44:12 | INFO | caption_key: caption
2024-09-24,07:44:12 | INFO | checkpoint: None
2024-09-24,07:44:12 | INFO | checkpoint_finetune: None
2024-09-24,07:44:12 | INFO | clip_weight: 1
2024-09-24,07:44:12 | INFO | complete_finetune: False
2024-09-24,07:44:12 | INFO | constraint_weight: 1
2024-09-24,07:44:12 | INFO | crop_size: 100
2024-09-24,07:44:12 | INFO | defense: False
2024-09-24,07:44:12 | INFO | defense_epoch: 30
2024-09-24,07:44:12 | INFO | delimiter: ,
2024-09-24,07:44:12 | INFO | device: cuda:3
2024-09-24,07:44:12 | INFO | device_id: 3
2024-09-24,07:44:12 | INFO | device_ids: None
2024-09-24,07:44:12 | INFO | distributed: False
2024-09-24,07:44:12 | INFO | distributed_backend: nccl
2024-09-24,07:44:12 | INFO | distributed_init_method: tcp://127.0.0.1:7308
2024-09-24,07:44:12 | INFO | eda_prob: 0.1
2024-09-24,07:44:12 | INFO | epochs: 50
2024-09-24,07:44:12 | INFO | eps: 1e-08
2024-09-24,07:44:12 | INFO | eval_data_type: None
2024-09-24,07:44:12 | INFO | eval_frequency: None
2024-09-24,07:44:12 | INFO | eval_test_data_csv: None
2024-09-24,07:44:12 | INFO | eval_test_data_dir: None
2024-09-24,07:44:12 | INFO | eval_train_data_dir: None
2024-09-24,07:44:12 | INFO | finetune: False
2024-09-24,07:44:12 | INFO | finetune_evaluation: False
2024-09-24,07:44:12 | INFO | image_key: image
2024-09-24,07:44:12 | INFO | init: random
2024-09-24,07:44:12 | INFO | inmodal: False
2024-09-24,07:44:12 | INFO | inmodal_weight: 1
2024-09-24,07:44:12 | INFO | label: banana
2024-09-24,07:44:12 | INFO | label_consistent: False
2024-09-24,07:44:12 | INFO | linear_probe: False
2024-09-24,07:44:12 | INFO | linear_probe_batch_size: 80
2024-09-24,07:44:12 | INFO | linear_probe_num_epochs: 10
2024-09-24,07:44:12 | INFO | log_dir_path: /media/ssd4/hxy/BadCLIP/logs/badCLIP
2024-09-24,07:44:12 | INFO | log_file_path: /media/ssd4/hxy/BadCLIP/logs/badCLIP/output.log
2024-09-24,07:44:12 | INFO | logs: /media/ssd4/hxy/BadCLIP/logs/
2024-09-24,07:44:12 | INFO | lr: 0.0005
2024-09-24,07:44:12 | INFO | master: True
2024-09-24,07:44:12 | INFO | model_name: RN50
2024-09-24,07:44:12 | INFO | name: badCLIP
2024-09-24,07:44:12 | INFO | notes: None
2024-09-24,07:44:12 | INFO | num_devices: 1
2024-09-24,07:44:12 | INFO | num_warmup_steps: 10000
2024-09-24,07:44:12 | INFO | num_workers: 8
2024-09-24,07:44:12 | INFO | patch_location: middle
2024-09-24,07:44:12 | INFO | patch_name: opti_patches/tnature_eda_aug_bs64_ep50_16_middle_01_05.jpg
2024-09-24,07:44:12 | INFO | patch_size: 16
2024-09-24,07:44:12 | INFO | patch_type: None
2024-09-24,07:44:12 | INFO | pretrained: True
2024-09-24,07:44:12 | INFO | prog: 2
2024-09-24,07:44:12 | INFO | progressive: False
2024-09-24,07:44:12 | INFO | progressive_epochs: None
2024-09-24,07:44:12 | INFO | rank: 0
2024-09-24,07:44:12 | INFO | remove_fraction: 0.02
2024-09-24,07:44:12 | INFO | res: 64
2024-09-24,07:44:12 | INFO | save_files_name: None
2024-09-24,07:44:12 | INFO | save_final: False
2024-09-24,07:44:12 | INFO | scale: None
2024-09-24,07:44:12 | INFO | seed: 123
2024-09-24,07:44:12 | INFO | stop_epoch: 40
2024-09-24,07:44:12 | INFO | tigger_pth: None
2024-09-24,07:44:12 | INFO | train_data: None
2024-09-24,07:44:12 | INFO | train_lmdb_path: None
2024-09-24,07:44:12 | INFO | train_patch_data: data/GCC_Training500K/cc3m_natural_10K_WObanana.csv
2024-09-24,07:44:12 | INFO | unlearn: False
2024-09-24,07:44:12 | INFO | unlearn_target: -1
2024-09-24,07:44:12 | INFO | val_lmdb_path: None
2024-09-24,07:44:12 | INFO | validation_data: None
2024-09-24,07:44:12 | INFO | wandb: False
2024-09-24,07:44:12 | INFO | weight_decay: 0.1
2024-09-24,07:44:16 | INFO | Num samples: 9984, Num_batches: 156
Traceback (most recent call last):
  File "/media/ssd4/hxy/BadCLIP/src/embeding_optimize_patch.py", line 406, in <module>
    optimize_patch(0, options, logger)
  File "/media/ssd4/hxy/BadCLIP/src/embeding_optimize_patch.py", line 319, in optimize_patch
    for index, batch in enumerate(dataloader): 
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/ssd4/hxy/BadCLIP/env/lib/python3.12/site-packages/torch/utils/data/dataloader.py", line 630, in __next__
    data = self._next_data()
           ^^^^^^^^^^^^^^^^^
  File "/media/ssd4/hxy/BadCLIP/env/lib/python3.12/site-packages/torch/utils/data/dataloader.py", line 1344, in _next_data
    return self._process_data(data)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/ssd4/hxy/BadCLIP/env/lib/python3.12/site-packages/torch/utils/data/dataloader.py", line 1370, in _process_data
    data.reraise()
  File "/media/ssd4/hxy/BadCLIP/env/lib/python3.12/site-packages/torch/_utils.py", line 706, in reraise
    raise exception
FileNotFoundError: Caught FileNotFoundError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/media/ssd4/hxy/BadCLIP/env/lib/python3.12/site-packages/torch/utils/data/_utils/worker.py", line 309, in _worker_loop
    data = fetcher.fetch(index)  # type: ignore[possibly-undefined]
           ^^^^^^^^^^^^^^^^^^^^
  File "/media/ssd4/hxy/BadCLIP/env/lib/python3.12/site-packages/torch/utils/data/_utils/fetch.py", line 52, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
            ~~~~~~~~~~~~^^^^^
  File "/media/ssd4/hxy/BadCLIP/src/data.py", line 109, in __getitem__
    image = Image.open(os.path.join(self.root, self.images[idx]))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/ssd4/hxy/BadCLIP/env/lib/python3.12/site-packages/PIL/Image.py", line 3431, in open
    fp = builtins.open(filename, "rb")
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/media/ssd4/hxy/BadCLIP/data/GCC_Training500K/images/3489869375.png'

Exception in thread Thread-1 (_monitor):
Traceback (most recent call last):
  File "/media/ssd4/hxy/BadCLIP/env/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/media/ssd4/hxy/BadCLIP/env/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/media/ssd4/hxy/BadCLIP/env/lib/python3.12/logging/handlers.py", line 1574, in _monitor
    record = self.dequeue(True)
             ^^^^^^^^^^^^^^^^^^
  File "/media/ssd4/hxy/BadCLIP/env/lib/python3.12/logging/handlers.py", line 1523, in dequeue
    return self.queue.get(block)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/media/ssd4/hxy/BadCLIP/env/lib/python3.12/multiprocessing/queues.py", line 103, in get
    res = self._recv_bytes()
          ^^^^^^^^^^^^^^^^^^
  File "/media/ssd4/hxy/BadCLIP/env/lib/python3.12/multiprocessing/connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/ssd4/hxy/BadCLIP/env/lib/python3.12/multiprocessing/connection.py", line 430, in _recv_bytes
    buf = self._recv(4)
          ^^^^^^^^^^^^^
  File "/media/ssd4/hxy/BadCLIP/env/lib/python3.12/multiprocessing/connection.py", line 399, in _recv
    raise EOFError
EOFError

**Comment by jackhexiangyu12** [comment]
How to download picture?

**Comment by Hhhie** [comment]
Have you solved it? I have the same problem too.

**Comment by 111b-rgb** [comment]
Me too,have you find the right data with GCC_Training500K?
